export const homeMenuList = [
    { screenName: "Reanimated - square" },
    { screenName: "Police siren" },
    { screenName: "iPhone sounde slider" },
    { screenName: "PanHandler - moving square" },
    { screenName: "Tacking status" },
    { screenName: "Card flip" },
    { screenName: "Reanimated - layout animation" },
    { screenName: "Input with animatied show password" },
    { screenName: "React native skia - bouncing ball" },
    { screenName: "React native local server" },
    { screenName: "React native custom slider" },
    { screenName: "React native custom round slider" },
    { screenName: "React native parallax slider" },
]