export const homeMenuList = [
    { screenName: "Reanimated - square" },
    { screenName: "Police siren" },
    { screenName: "iPhone sounde slider" },
    { screenName: "PanHandler - moving square" },
    { screenName: "Tacking status" },
    { screenName: "Card flip" },
    { screenName: "Reanimated - layout animation" },
    { screenName: "Input with animated show password" },
    { screenName: "React native skia - bouncing ball" },
    { screenName: "React native local server" },
    { screenName: "Custom slider" },
    { screenName: "Custom round slider" },
    { screenName: "Parallax slider" },
    { screenName: "Box animation with gestures" },
    { screenName: "Animated custom tab bar" },
    { screenName: "Voice commands" },
]